### ISSUE TITLE
Not able to run the project in mac os

### ISSUE THREAD

**Issue by AkshayDevkate** [MahmudulAlam/Automatic-Identification-and-Counting-of-Blood-Cells#11] opened 2021-01-16 19:58 UTC
Hello I am using mac 

My Laptop configuration 
MacOS Catalina
Version- 10.15.3 (19D76)
Processor - 1.8 GHz Dual-Core Intel Core i5
Graphics - Intel HD Graphics 6000 1536 MB

 i tried run 
>python3 blood_cell_detection.py
i got following errors

`Akshays-MacBook-Air-2:Automatic-Identification-and-Counting-of-Blood-Cells-master akshaydevkate$ python3 testing_dataset.py
Traceback (most recent call last):
  File "testing_dataset.py", line 6, in <module>
    from darkflow.net.build import TFNet
  File "/Users/akshaydevkate/Downloads/Automatic-Identification-and-Counting-of-Blood-Cells-master/darkflow/net/build.py", line 1, in <module>
    import tensorflow as tf
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/__init__.py", line 84, in <module>
    from tensorflow.python import keras
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/keras/__init__.py", line 27, in <module>
    from tensorflow.python.keras import models
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/keras/models/__init__.py", line 21, in <module>
    from tensorflow.python.keras._impl.keras.models import load_model
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/keras/_impl/keras/__init__.py", line 21, in <module>
    from tensorflow.python.keras._impl.keras import activations
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/keras/_impl/keras/activations.py", line 23, in <module>
    from tensorflow.python.keras._impl.keras import backend as K
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/keras/_impl/keras/backend.py", line 38, in <module>
    from tensorflow.python.layers import base as tf_base_layers
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/layers/base.py", line 25, in <module>
    from tensorflow.python.keras import backend
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/keras/backend/__init__.py", line 22, in <module>
    from tensorflow.python.keras._impl.keras.backend import abs
ImportError: cannot import name 'abs' from partially initialized module 'tensorflow.python.keras._impl.keras.backend' (most likely due to a circular import) (/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/keras/_impl/keras/backend.py)`

Will i be able to run the code in mac ? some where i tried to install tensorflow-gpu from terminal i got the following output

`ERROR: Could not find a version that satisfies the requirement TensorFlow-GPU==1.11.0
ERROR: No matching distribution found for TensorFlow-GPU==1.11.0`

After this i  uploaded the files on drive and mounted to colab and after executing 

>!python3 blood_cell_detection.py
the above command 

i got the following errors

`2021-01-16 19:46:35.482977: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "blood_cell_detection.py", line 5, in <module>
    from darkflow.net.build import TFNet
  File "/content/darkflow/net/build.py", line 5, in <module>
    from .ops import op_create, identity
  File "/content/darkflow/net/ops/__init__.py", line 1, in <module>
    from .simple import *
  File "/content/darkflow/net/ops/simple.py", line 1, in <module>
    import tensorflow.contrib.slim as slim
ModuleNotFoundError: No module named 'tensorflow.contrib'`

Thanks in advance :)

**Comment by kieungoctrang** [comment] 2021-02-26 13:04
Duplicate of #

**Comment by kieungoctrang** [comment] 2021-02-26 13:04
> Duplicate of #

**Closed** 2021-06-29 14:02 UTC
